routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) {
        return redirect('lineas');
    } else {
        return view('auth/login');
    }

    //return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/register_cedula', 'Auth\RegisterController@registerCedula')->name('register-cedula');

//MIDDLEWARES
Route::middleware(['auth'])->group(function() {
    /*
    Route::get('map', function () {
        return view('map.index');
    });
    */

    //Map routes
    Route::resource('map', 'Map\MapController');
    Route::post('map-direction', 'Map\MapController@mapDirection')->name('map-direction');

    //Account routes
    Route::resource('perfil', 'Perfil\PerfilController');

    // Products routes
    Route::resource('productos', 'Producto\ProductoController');

    // Items routes
    Route::resource('items', 'Item\ItemController', ['only' => ['index', 'show']]);

    // Linea routes
    Route::resource('lineas', 'Linea\LineaController');
    Route::get('categorias/{linea}', 'Linea\LineaController@lineasCategoriaProductos')->name('lineas-categoria-productos');

    //Arindex routes
    Route::resource('arindex', 'Arindex\ArindexController', ['only' => ['index', 'show']]);

    //Cart routes
    Route::resource('cart', 'Cart\CartController');
    Route::get('addItem/{id}', 'Cart\CartController@addItem')->name('add-item');
    Route::get('clearCart', 'Cart\CartController@clearCart')->name('clear-cart');
    Route::get('addItemsGroup/{items}', 'Cart\CartController@addItemsGroup')->name('add-items-group');

    //Factura route
    Route::get('factura', function() {
        /*
        $cliente = \App\Models\ARCLIENTE::where("CODIGO", "9999999999")
            ->orWhere("CODIGO", "9999999999999")
            ->first();
        */
        $cliente = \Illuminate\Support\Facades\Auth::User();

        return view('cart.factura')->with('cliente', $cliente);
    })->name('factura');

    Route::resource('pedido', 'TBCINV\TBCINVController');
    Route::get('historial_pedidos', 'TBCINV\TBCINVController@historialPedidos')->name('historial-pedidos');
    Route::get('consultar_pedidos', 'TBCINV\TBCINVController@consultarPedidos')->name('consultar-pedidos');

    Route::resource('detalle_pedido', 'TBDINV\TBDINVController');

    //Pdf
    Route::resource('pdf', 'PDF\PdfController');
});

app/Http/Controllers/Cart/CartController.php
<?php

namespace App\Http\Controllers\Cart;

use App\Models\ARBODB;
//use Darryldecode\Cart\Cart;
use App\Models\TBBIM_TIPOCL;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Mockery\CountValidator\Exception;

use Cart;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cartCollection = Cart::getContent();
        $data = array_reverse($cartCollection->toArray());

        return view('cart.index')->with('data', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->quantity == 0) {
            Cart::remove($id);
            session()->flash('flash_message', '¡Producto eliminado del carrito!');
            session()->flash('alert_class', 'alert-success'); //Tambien hay la clase alert-warning
        } else {
            Cart::update($id, array(
                'quantity' => array(
                    'relative' => false,
                    'value' => $request->quantity
                ),
            ));
            session()->flash('flash_message', '¡Cantidad del producto actualizada!');
            session()->flash('alert_class', 'alert-success'); //Tambien hay la clase alert-warning
        }

        return response()->json(['success' => true]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Cart::remove($id);

        session()->flash('flash_message', '¡Producto eliminado del carrito!');
        session()->flash('alert_class', 'alert-success'); //Tambien hay la clase alert-warning

        return redirect()->route('cart.index');
    }

    public function addItem(Request $request, $id) {
        try {
            $producto = ARBODB::find($id);
            $precio = $this->getPrecioCliente($producto);

             Cart::add(array(
                'id' => $producto->NUMERO_ITEM,
                'name' => $producto->DESCRIPCION,
                'price' => $precio,
                'quantity' =>  $request->cantidad,
                'attributes' => array()
            ));
        } catch (Exception $ex) {
            return response()->json(['success' => false]);
        } finally {
            $cantidad = Cart::getTotalQuantity();

            return response()->json(['success' => true, 'cantidad' => $cantidad]);
        }
    }

    public function getPrecioCliente($producto) {
        $cliente = Auth::user();
        $tipoclte = $cliente->TIPOCLTE;
        if ($tipoclte == "0") {
            $tipoclte = "1";
        }

        $nivel_precio_cliente = TBBIM_TIPOCL::find($tipoclte)->TIP_NIVELPRE;
        switch ($nivel_precio_cliente) {
            case 1: {
                return $producto->PRECIOD_VTA_1;
            }
            case 2: {
                return $producto->PRECIOD_VTA_2;
            }
            case 3: {
                return $producto->PRECIOD_VTA_3;
            }
            case 4: {
                return $producto->PRECIOD_VTA_4;
            }
            case 5: {
                return $producto->PRECIOD_VTA_5;
            }
            case 6: {
                return $producto->PRECIOD_VTA_6;
            }
            case 7: {
                return $producto->PRECIOD_VTA_7;
            }
            case 8: {
                return $producto->PRECIOD_VTA_8;
            }
        }
    }

    public function addItemsGroup(Request $request, $items) {
        try {
            $array_items = json_decode($items);

            foreach ($array_items as $item) {
                $producto = ARBODB::find($item->numeroItem);
                $precio = $this->getPrecioCliente($producto);
                Cart::add(array(
                    'id' => $producto->NUMERO_ITEM,
                    'name' => $producto->DESCRIPCION,
                    'price' => $precio,
                    'quantity' =>  $item->cantidad,
                    'attributes' => array()
                ));
            }

            session()->flash('flash_message', '¡Productos agregados al carrito!');
            session()->flash('alert_class', 'alert-success'); //Tambien hay la clase alert-warning
        } catch (Exception $ex) {
            return view('errors.405');
        } finally {
            return redirect()->route('cart.index');
        }
    }

    public function clearCart() {
        Cart::clear();

        return redirect()->route('cart.index');
    }
}

resources/views/cart/factura.blade.php
@extends('layouts.app')

@section('title', 'Factura')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Datos de facturación</div>

                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('pedido.store') }}" onsubmit="disableButton()">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('identificacion') ? ' has-error' : '' }}">
                                <label for="identificacion" class="col-md-4 control-label">Identificacion</label>

                                <div class="col-md-6">
                                    <!--
                                    <p >{{$cliente->CODIGO}}</p>
                                    -->
                                    <input id="identificacion" type="text" class="form-control" name="identificacion" value="{{$cliente->CODIGO}}" required autofocus>

                                    @if ($errors->has('identificacion'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('identificacion') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-4 control-label">Nombres</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name" value="{{$cliente->NOMBRE}}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('apellido') ? ' has-error' : '' }}">
                                <label for="apellido" class="col-md-4 control-label">Apellidos</label>

                                <div class="col-md-6">
                                    <input id="apellido" type="text" class="form-control" name="apellido" value="{{$cliente->APELLIDO}}" required autofocus>

                                    @if ($errors->has('apellido'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('apellido') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="email" class="col-md-4 control-label">Correo Electrónico</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control" name="email" value="{{$cliente->MAIL}}" required>

                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('direccion') ? ' has-error' : '' }}">
                                <label for="direccion" class="col-md-4 control-label">Dirección de Domicilio</label>

                                <div class="col-md-6">
                                    <input id="direccion" type="text" class="form-control" name="direccion" value="{{$cliente->DOMICILIO}}" required autofocus>

                                    @if ($errors->has('direccion'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('direccion') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('telefono') ? ' has-error' : '' }}">
                                <label for="telefono" class="col-md-4 control-label">Teléfono</label>

                                <div class="col-md-6">
                                    <input id="telefono" type="number" class="form-control" name="telefono" value="{{$cliente->CL_CELULAR}}" required autofocus>

                                    @if ($errors->has('telefono'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('telefono') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="form-check form-check-inline col-md-offset-4 col-md-4 ">
                                    <input class="form-check-input" type="radio" name="opcion_entrega" id="inlineRadio1" value="2" checked="checked">
                                    <label class="form-check-label" for="inlineRadio1">Entrega a domicilio</label>
                                </div>
                                <div class="form-check form-check-inline col-md-4">
                                    <input class="form-check-input" type="radio" name="opcion_entrega" id="inlineRadio2" value="1">
                                    <label class="form-check-label" for="inlineRadio2">Para retirar</label>
                                </div>
                            </div>

                            <hr style="border-top: 4px double #cecece;">

                            <div class="form-group" style="display: flex;">
                                    <div class="col-md-2 col-sm-2 col-xs-3 col-md-offset-4">
                                        <p>SUBTOTAL:</p>
                                    </div>
                                    <div class="col-md-6 col-sm-3 col-xs-3">
                                        <p>{{ round(Cart::getSubtotal(), 2) }} $</p>
                                    </div>
                            </div>

                            <div class="form-group"  style="display: flex;">
                                <div class="col-md-2 col-sm-2 col-xs-3 col-md-offset-4">
                                    <p>IVA 12%:</p>
                                </div>
                                <div class="col-md-6 col-sm-3 col-xs-3">
                                    <p>{{ round(Cart::getSubtotal() *0.12, 2)}} $</p>
                                </div>
                            </div>

                            <div class="form-group"  style="display: flex;">
                                <div class="col-md-2 col-sm-2  col-xs-3 col-md-offset-4">
                                    <p>TOTAL:</p>
                                </div>
                                <div class="col-md-6 col-sm-3 col-xs-3">
                                    <p>{{ round(Cart::getTotal() * 1.12, 2) }} $</p>
                                </div>
                            </div>

                            <div class="form-group"  style="display: flex;">
                                <div class="col-md-2 col-md-offset-4">
                                    <a href="{{route('cart.index')}}" class="btn btn-danger">
                                        VOLVER
                                    </a>
                                </div>
                                <div class="col-md-6">
                                    <input type="submit" id="realizar-pedido" class="btn btn-danger" value="REALIZAR PEDIDO"/>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function disableButton() {
            $("#realizar-pedido").attr("disabled", true);
            $("#realizar-pedido").val("REGISTRANDO PEDIDO...")
        }
    </script>
@endsection

resources/views/cart/index.blade.php
@extends('layouts.app')

@section('title', 'Carrito de compras')

@section('content')
    <div class="container" style="margin-bottom: 22px">
        {{--
        <h1>Tu pedido</h1>
        --}}
        <hr>

        @if (!Cart::isEmpty())
            <div class="row" style="margin-bottom: 20px">
                <div class="col-xs-12 col-sm-4 col-md-3">
                    <a href="{{ route('lineas.index') }}" class="btn btn-primary btn-lg">Continuar comprando</a>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-3">
                    <!--
                    <a href="{{route('factura')}}" class="btn btn-success btn-lg">Realizar pedido</a>
                    -->
                    <button class="btn btn-success btn-lg" id="pedido-factura">Realizar pedido</button>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-6">
                    <form action="{{ route('clear-cart') }}" method="GET">
                        {!! csrf_field() !!}
                        <input type="hidden" name="_method" value="DELETE">
                        <button type="submit" class="btn btn-danger btn-lg pull-right" onclick="return confirm('¿Seguro que desea vaciar carrito de pedido?')">
                            <svg class="bi bi-trash2-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M2.037 3.225l1.684 10.104A2 2 0 0 0 5.694 15h4.612a2 2 0 0 0 1.973-1.671l1.684-10.104C13.627 4.224 11.085 5 8 5c-3.086 0-5.627-.776-5.963-1.775z"/>
                                <path fill-rule="evenodd" d="M12.9 3c-.18-.14-.497-.307-.974-.466C10.967 2.214 9.58 2 8 2s-2.968.215-3.926.534c-.477.16-.795.327-.975.466.18.14.498.307.975.466C5.032 3.786 6.42 4 8 4s2.967-.215 3.926-.534c.477-.16.795-.327.975-.466zM8 5c3.314 0 6-.895 6-2s-2.686-2-6-2-6 .895-6 2 2.686 2 6 2z"/>
                            </svg>
                        </button>
                    </form>
                </div>
            </div>

            <h4>Dirección de entrega</h4>
            <div class="row" style="margin-bottom: 10px">
                <div class="col-xs-6 col-sm-4 col-md-3">
                    <p id="direccion-entrega">No seleccionado</p>
                </div>

                <div class="col-xs-6 col-sm-4 col-md-3">
                    <a href="{{ url('/map') }}" class="btn btn-danger">CAMBIAR</a>
                </div>

            </div>

            <div class="panel panel-default" >
                <div class="panel-heading" style="font-weight: bold; font-size: 18px;">
                    Tu pedido
                    <!--
                    <a class="pull-right" href="{{route('pdf.index')}}" target="_blank" title="Descargar PDF" style="margin-right: 10px;">
                        <i class="fa fa-download" aria-hidden="true"></i>
                    </a>
                    -->
                </div>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Total</th>
                        <th class="column-spacer"></th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach ($data as $item)
                        <tr>
                            <td width="35%"><a href="{{ route('productos.show', $item['id']) }}">{{ $item['name'] }}</a></td>
                            <td width="45%">
                                <div class="col-xs-6 col-sm-6 col-md-6" style="padding-left: 0px; padding-right: 0px">
                                    {!!Form::number('cantidad', $item['quantity'], ['class' => 'form-control', 'min' => '0','required', 'id' => 'qty-'.$item['id']]) !!}
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6" style="padding-left: 0px; padding-right: 0px">
                                    <button type="submit" class="btn btn-primary btn-edit" data-id="{{$item['id']}}">
                                        <i class="fa fa-refresh" aria-hidden="true"></i>
                                    </button>
                                </div>
                            </td>
                            <td width="15%">$ {{$item['price'] * $item['quantity']}}</td>
                            <td width="5%">
                                {!! Form::open(['route' =>  ['cart.destroy', $item['id']] , 'method' => 'DELETE']) !!}
                                {!! csrf_field() !!}
                                <button type="submit" class="btn btn-danger btn-sm" value="Eliminar" onclick="return confirm('¿Seguro que desea eliminarlo?')">
                                    <svg class="bi bi-trash-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
                                    </svg>
                                </button>
                                {!!Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    <tr>
                        <td class="table-image"></td>
                        <td></td>
                        <td class="small-caps table-bg" style="text-align: right">Subtotal</td>
                        <td>$ {{ Cart::getSubtotal() }}</td>
                        <td></td>
                        <td></td>
                    </tr>

                    <tr class="border-bottom">
                        <td class="table-image"></td>
                        <td style="padding: 40px;"></td>
                        <td class="small-caps table-bg" style="text-align: right">Total a pagar</td>
                        <td class="table-bg">$ {{ Cart::getTotal() }}</td>
                        <td class="column-spacer"></td>
                        <td></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        @else
            <h3>No tienes items en tu carrito de compras</h3>
            <a href="{{ route('lineas.index') }}" class="btn btn-primary btn-lg">Continuar comprando</a>
        @endif
    </div>

    <script>
        function initMap() {
            @if(Session::has('latitud') && Session::has('longitud'))
                var latitud = "{{Session::get('latitud')}}";
                var longitud = "{{Session::get('longitud')}}";

                var direccion_entrega =  document.getElementById('direccion-entrega');

                var geocoder = new google.maps.Geocoder();

                var latlng = new google.maps.LatLng(latitud,longitud);
                geocoder.geocode({
                    'latLng': latlng
                }, function (results, status) {
                    if (status === google.maps.GeocoderStatus.OK) {
                        if (results[0]) {
                            direccion_entrega.innerHTML = results[0].formatted_address;
                            console.log(results[0].formatted_address);
                        } else {
                            alert('No results found');
                        }
                    } else {
                        alert('Geocoder failed due to: ' + status);
                    }
                });
            @endif
        }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?libraries=places&key={{env('GOOGLE_API_KEY')}}&callback=initMap"></script>
@endsection

@section('extra-js')
    <script>
        $(document).ready(function(){
            $("a.submit").click(function(){
                var id = $(this).attr('id');
                console.log(id);
                if (confirm('¿Seguro que desea eliminarlo?')) {
                    document.getElementById("form-"+id).submit();
                }

            });
        });

        (function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $(".btn-edit").click(function(e) {
                var id = $(this).attr('data-id');
                var qty = $('#qty-' + id).val();

                $.ajax({
                    type: "PATCH",
                    url: '{{ url("/cart") }}' + '/' + id,
                    data: {
                        'quantity': qty,
                    },
                    success: function(data) {
                        window.location.href = '{{ url('/cart') }}';
                    }
                });
            });
        })();

        $("#pedido-factura").click( function() {
            @if(Session::has('latitud') && Session::has('longitud'))
                 var lat = {{Session::get('latitud')}}
                 var lon = {{Session::get('longitud')}}
                 console.log(lat);
                 console.log(lon);
                 window.location.href = "{{route('factura')}}";
            @else
                console.log('NO HAY COORDENADAS');
                toastr.warning("Elija dirección de destino antes de continuar. Presione el botón CAMBIAR para elegir su dirección de entrega");
            @endif
        });
    </script>
@endsection