routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) {
        return redirect('lineas');
    } else {
        return view('auth/login');
    }

    //return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/register_cedula', 'Auth\RegisterController@registerCedula')->name('register-cedula');

//MIDDLEWARES
Route::middleware(['auth'])->group(function() {
    /*
    Route::get('map', function () {
        return view('map.index');
    });
    */

    //Map routes
    Route::resource('map', 'Map\MapController');
    Route::post('map-direction', 'Map\MapController@mapDirection')->name('map-direction');

    //Account routes
    Route::resource('perfil', 'Perfil\PerfilController');

    // Products routes
    Route::resource('productos', 'Producto\ProductoController');

    // Items routes
    Route::resource('items', 'Item\ItemController', ['only' => ['index', 'show']]);

    // Linea routes
    Route::resource('lineas', 'Linea\LineaController');
    Route::get('categorias/{linea}', 'Linea\LineaController@lineasCategoriaProductos')->name('lineas-categoria-productos');

    //Arindex routes
    Route::resource('arindex', 'Arindex\ArindexController', ['only' => ['index', 'show']]);

    //Cart routes
    Route::resource('cart', 'Cart\CartController');
    Route::get('addItem/{id}', 'Cart\CartController@addItem')->name('add-item');
    Route::get('clearCart', 'Cart\CartController@clearCart')->name('clear-cart');
    Route::get('addItemsGroup/{items}', 'Cart\CartController@addItemsGroup')->name('add-items-group');

    //Factura route
    Route::get('factura', function() {
        /*
        $cliente = \App\Models\ARCLIENTE::where("CODIGO", "9999999999")
            ->orWhere("CODIGO", "9999999999999")
            ->first();
        */
        $cliente = \Illuminate\Support\Facades\Auth::User();

        return view('cart.factura')->with('cliente', $cliente);
    })->name('factura');

    Route::resource('pedido', 'TBCINV\TBCINVController');
    Route::get('historial_pedidos', 'TBCINV\TBCINVController@historialPedidos')->name('historial-pedidos');
    Route::get('consultar_pedidos', 'TBCINV\TBCINVController@consultarPedidos')->name('consultar-pedidos');

    Route::resource('detalle_pedido', 'TBDINV\TBDINVController');

    //Pdf
    Route::resource('pdf', 'PDF\PdfController');
});

resources/views/pedido/detalle_pedido.blade.php
@extends('layouts.app')

@section('title', 'Detalle Pedido')

@section('content')
    <div class="container">
        <div class="row">
            <!-- Title -->
            <ol class="breadcrumb">
                <li><a href="{{ route('historial-pedidos') }}">Historial de pedidos</a></li>
                @if(isset($pedido))
                    <li class="active">Pedido # {{$pedido->CINV_SEC}}</li>
                @endif
            </ol>
        </div>

        <div class="row">
            {!!Form::label('fecha', 'Fecha:', ['class' => 'control-label col-xs-2 col-sm-1 col-md-1'])!!}
            <p class="col-xs-3 col-sm-3 col-md-3"> {{$pedido->CINV_FECING}}</p>
        </div>
        <div class="row">
            {!!Form::label('total', 'Total:', ['class' => 'control-label  col-xs-2 col-sm-1 col-md-1'])!!}
            <p class="col-xs-3 col-sm-34 col-md-3"> {{round($pedido->tbdinvs()->sum('DINV_VTA'), 2)}}</p>
        </div>

        <hr>

        @if(isset($detalles_pedido))
            <table id="table-productos" class="table table-bordered">
                <thead>
                <th>Linea</th>
                <th>Descripcion</th>
                <th>Cantidad</th>
                <th>Precio Unitario</th>
                <th>Valor total</th>
                </thead>

                <tbody>
                    @foreach($detalles_pedido as $key=>$detalle_pedido)
                        @if(($key%2) == 0)
                            <tr style="background-color: #e8e8e8;" id="tr-{{$detalle_pedido->DINV_LINEA}}">
                        @else
                            <tr id="tr-{{$detalle_pedido->DINV_LINEA}}">
                        @endif
                                <td>{{$detalle_pedido->DINV_LINEA}}</td>
                                <td>{{$detalle_pedido->producto->DESCRIPCION}}</td>
                                <td>{{$detalle_pedido->DINV_CANT}}</td>
                                <td>{{round($detalle_pedido->STOCK1, 2)}}</td>
                                <td>{{round($detalle_pedido->DINV_VTA, 2)}}</td>
                            </tr>
                     @endforeach
                </tbody>

            </table>
        @endif
    </div>
@endsection

resources/views/pedido/historial_pedidos.blade.php
@extends('layouts.app')

@section('title', 'Historial de pedidos')

@section('content')
    {{--
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    HISTORIAL DE PEDIDOS
    <p>Date: <input type="text" id="datepicker" class="form-control"></p>

    <script type="text/javascript">
        $( "#datepicker" ).datepicker();
    </script>
    --}}

    <!-- Fuente: http://www.daterangepicker.com/ -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

    {{--
    <input type="text" name="datetimes"  class="form-control"/>
    --}}

    <div class="container">
        <div class="form-group">
            <div class="row">
                {!! Form::model(Request::all(), ['route' => 'consultar-pedidos', 'method' => 'GET']) !!}
                <div class="col-xs-12 col-sm-4 col-md-4">
                    {!!Form::label('fecha_inicio_fin', 'Fecha Inicio:', ['class' => 'control-label'])!!}
                    {!!Form::text('fecha_inicio', null, ['class' => 'form-control', 'placeholder' => 'Fecha Inicio...', 'aria-descridbedby' => 'search', 'required' => true]) !!}
                    <br>
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    {!!Form::label('fecha_inicio_fin', 'Fecha Fin:', ['class' => 'control-label'])!!}
                    {!!Form::text('fecha_fin', null, ['class' => 'form-control', 'placeholder' => 'Fecha Fin...', 'aria-descridbedby' => 'search', 'required' => true]) !!}
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <br>
                    <button type="submit" class="btn btn-default btn-search-product">Buscar</button>
                </div>
                {!!Form::close() !!}
            </div>
        </div>

        @if(isset($pedidos))
        <table id="table-productos" class="table table-bordered">
            <thead>
            <th>Secuencia</th>
            <th>Fecha</th>
            <th>Valor total</th>
            <th>Acción</th>
            </thead>

            <tbody>
            @foreach($pedidos as $key=>$pedido)
                @if(($key%2) == 0)
                    <tr style="background-color: #e8e8e8;" id="tr-{{$pedido->CINV_SEC}}">
                @else
                    <tr id="tr-{{$pedido->CINV_SEC}}">
                @endif
                        <td>{{$pedido->CINV_SEC}}</td>
                        <td>{{$pedido->CINV_FECING}}</td>
                        <td>{{round($pedido->tbdinvs()->sum('DINV_VTA'), 2)}}</td>
                        <td style="text-align: center;">
                            <a class="btn btn-warning" href="{{ route('detalle_pedido.show', $pedido->CINV_SEC) }}">Visualizar</a>
                        </td>
                    </tr>
            @endforeach
            </tbody>

        </table>
        @endif

        @if(isset($pedidos))
            <div class="text-center">
                {{ $pedidos->appends(Request::all())->links() }}
            </div>
        @endif
    </div>


    <script>
        /*
        $('input[name="datetimes"]').daterangepicker({
            timePicker: true,
            startDate: moment().startOf('hour'),
            endDate: moment().startOf('hour').add(32, 'hour'),
            locale: {
                format: 'DD/MM/YYYY'
            }
        });
        */

        $('input[name="fecha_inicio"]').daterangepicker({
            singleDatePicker: true,
            showDropdowns: true,
            locale: {
                format: 'DD/MM/YYYY'
            }
        });


        $('input[name="fecha_fin"]').daterangepicker({
            singleDatePicker: true,
            showDropdowns: true,
            locale: {
                format: 'DD/MM/YYYY'
            }
        });

        //$('input[name="fecha_inicio"]').val('');
        //$('input[name="fecha_fin"]').val('');
    </script>

@endsection